"""Machine-readable lineage registry for dashboard exports.

The registry is intentionally code-owned. Glossary workbooks can be generated
from it later, but exports should not depend on an external documentation file.
"""

from __future__ import annotations

from typing import Iterable


from utils.lineage.models import CodeReference, LineageSpec, ParameterSpec, SourceSpec


def _src(table: str, *columns: str) -> SourceSpec:
    return SourceSpec(table=table, columns=tuple(columns))


def _ref(file_glob: str, function_name: str) -> CodeReference:
    return CodeReference(file_glob=file_glob, function_name=function_name)


COMMON_ANALYSIS_FILTERS = (
    "Sidebar-Filter",
    "globale Kennzahl",
    "Top-N",
    "Sortierung",
    "Mindestgroesse",
)

ORG_PAGE = "Organisationseinheiten-Analyse"
ORG_SIM_PAGE = "Organisationseinheiten-Analyse Simulation"
JOB_PAGE = "Jobgruppen-Analyse"
JOB_SIM_PAGE = "Jobgruppen-Analyse Simulation"

ORG_FILE = "pages/*_Organisationseinheiten_Analyse.py"
ORG_SIM_FILE = "pages/*_Organisationseinheiten_Simulation.py"
JOB_FILE = "pages/*_Jobfamily_Analyse.py"
JOB_SIM_FILE = "pages/*_Jobfamily_Simulation.py"
COMPACT_FILE = "pages/*_Kompakt.py"
COMPACT_SIM_PAGE_FILE = "pages/*_Kompakt_plus_Simulation.py"
COMPACT_SIM_EXPORT_FILE = "utils/compact_simulation_export.py"
DATA_INTEGRITY_FILE = "dataloader/data_integrity.py"
CLUSTER_MANAGER_FILE = "dataloader/cluster_manager.py"
UPLOAD_TEMPLATES_FILE = "dataloader/upload_templates.py"
IMPORT_EXPORT_FILE = "utils/import_export.py"


LINEAGE_SPECS: tuple[LineageSpec, ...] = (
    LineageSpec(
        lineage_id="7-01",
        label="Kompakt plus Simulation Gesamt-Export",
        page="Kompakt plus Simulation",
        section="Excel-Gesamtexport",
        display_type="Mehrblatt-Workbook",
        unit="Parameter, Koepfe, MAK, Demografie, Audit- und Validierungswerte",
        data_basis="Zuletzt berechneter Future-Snapshot und optionaler Status-Quo-Snapshot",
        sources=(
            _src("compact_sim_prepared_df", "PersNr", "Jobfamily", "Organisationseinheit", "MAK_Calculated", "MAK_Reporting"),
            _src("compact_sim_metadata", "base_date", "target_date", "used_simulation", "abgaenge_events", "zugaenge_events"),
            _src("compact_sim_audit_tables"),
            _src("compact_sim_abgaenge_params"),
            _src("compact_sim_zugaenge_params"),
        ),
        calculations=(
            _ref(COMPACT_SIM_PAGE_FILE, "main"),
            _ref(COMPACT_SIM_EXPORT_FILE, "build_compact_simulation_export_bytes"),
            _ref(COMPACT_SIM_EXPORT_FILE, "build_parameter_sheet"),
            _ref(COMPACT_SIM_EXPORT_FILE, "build_jobfamily_summary"),
            _ref(COMPACT_SIM_EXPORT_FILE, "build_jobfamily_demographics"),
            _ref(COMPACT_SIM_EXPORT_FILE, "_executive_summary_sheet"),
            _ref(COMPACT_SIM_EXPORT_FILE, "_scope_check_sheet"),
            _ref(COMPACT_SIM_EXPORT_FILE, "_jobfamily_reporting_comparison"),
            _ref(COMPACT_SIM_EXPORT_FILE, "_full_workforce_comparison"),
            _ref(COMPACT_SIM_EXPORT_FILE, "_validation_sheet"),
        ),
        formula="Workbook aus Parameterblatt, Management-Sheets, Jobfamily-Summary, Demografie, Status-Quo-Vergleichen, Audit-Sheets und Validierungschecks; jedes Sheet wird aus dem Future-Snapshot, optionalem Status-Quo und den Simulationsparametern rekonstruiert.",
        filters=("Simulationsmodus Ist/Future", "Ziel-Stichtag", "Abgaenge-Parameter", "Zugaenge-Parameter", "Exklusions- und Clusterkontext"),
        data_lineage="Kompakt plus Simulation -> simulate_compact_snapshot -> compact_sim_prepared_df/session_state -> build_compact_simulation_export_bytes -> Mehrblatt-Workbook",
        tests=(
            "test_compact_plus_simulation_page_uses_lazy_export_with_default_lineage",
            "test_export_workbook_contains_parameters_and_result_sheets",
        ),
        validation_status="technisch bestaetigt",
        notes="Die Detailformeln einzelner Analyse-Sichten werden zusaetzlich ueber die IDs 10-xx und 11-xx im selben Workbook dokumentiert.",
    ),
    LineageSpec(
        lineage_id="1-01",
        label="Kompakt IST ohne Plan-SOLL",
        page="Kompakt",
        section="IST vs SOLL",
        display_type="Warnbox, KPI, Excel-Download",
        unit="Planstellenzeilen, Personen, MAK",
        data_basis="Kompakt-Vergleichsdaten",
        sources=(_src("comp_df", "Ist_ohne_Plan_Soll_Kategorie", "PersNr", "IST_MAK", "IST_EUR", "SOLL_MAK"),),
        calculations=(_ref(COMPACT_FILE, "_render_ist_ohne_plan_soll_warning"),),
        formula="Filter auf Ist_ohne_Plan_Soll_Kategorie != leer; Summen fuer Zeilen, Personen, IST_MAK und IST_EUR; Detaildownload mit relevanten Planstellen- und Personenspalten.",
        filters=("aktiver Kompakt-Filterkontext", "Kategorie IST ohne Plan-SOLL"),
        data_lineage="build_compact_compensation_planlevel_df -> comp_df -> _render_ist_ohne_plan_soll_warning -> Detail-Excel",
        tests=("test_render_ist_ohne_plan_soll_export_contains_lineage_report",),
        validation_status="technisch teilweise bestaetigt",
        notes="Testabdeckung fuer konkrete Detailwerte sollte in einer Folgeiteration ergaenzt werden.",
    ),
    LineageSpec(
        lineage_id="1-02",
        label="Kompakt Verguetung Fit",
        page="Kompakt",
        section="Verguetung Fit",
        display_type="Chart, Tabelle, Excel-Download",
        unit="MAK oder EUR",
        data_basis="Kompakt-Verguetungsdaten",
        sources=(_src("comp_df", "Soll_EG_H", "Soll_EG_I", "IST_MAK", "SOLL_MAK", "IST_EUR", "SOLL_EUR"),),
        calculations=(
            _ref(COMPACT_FILE, "render_compensation_band_fit_section"),
            _ref(COMPACT_FILE, "_build_compensation_band_fit_summary"),
        ),
        formula="Aggregation je Entgeltgruppen-Spanne; SOLL wird Passend, Abweichend, Vakanz, Nicht gefunden und Kapazitaetsluecke gegenuebergestellt.",
        filters=("aktiver Kompakt-Filterkontext", "globale Kennzahl MAK/EUR"),
        data_lineage="build_compact_compensation_planlevel_df -> _build_compensation_band_fit_summary -> chart/table/export",
        tests=("test_build_compensation_band_fit_summary_matches_hand_calculation",),
        validation_status="technisch bestaetigt",
    ),
    LineageSpec(
        lineage_id="1-03",
        label="Kompakt Soll-Ist Koepfe Spannenmatrix",
        page="Kompakt",
        section="IST vs SOLL Koepfe",
        display_type="Matrix, Excel-Download",
        unit="Planstellenanzahl",
        data_basis="Planstellenbasierte Soll/Ist-Koepfe-Auswertung",
        sources=(_src("work_df", "_Soll_EG_H", "_Soll_EG_I", "_Ist_EG", "Planstellennr", "Personalnummer"),),
        calculations=(
            _ref(COMPACT_FILE, "render_ist_soll_koepfe_tab"),
            _ref(COMPACT_FILE, "_build_soll_ist_band_pivot"),
        ),
        formula="Pivot nach Soll-EG-Spanne und tatsaechlicher Ist-EG; Gesamtzeile ist Summe aller Spalten.",
        filters=("aktiver Kompakt-Filterkontext", "gueltige Soll-Entgeltgruppe"),
        data_lineage="_build_soll_ist_pivot_raw_logic -> work_df -> _build_soll_ist_band_pivot -> Matrix-Excel",
        tests=("test_render_ist_soll_koepfe_tab_detail_excel_export_matches_charts_and_hover",),
        validation_status="technisch teilweise bestaetigt",
    ),
    LineageSpec(
        lineage_id="1-04",
        label="Kompakt Soll-Ist Koepfe Fit",
        page="Kompakt",
        section="IST vs SOLL Koepfe",
        display_type="Chart, Tabelle, Excel-Download",
        unit="Planstellenanzahl",
        data_basis="Planstellenbasierte Soll/Ist-Koepfe-Auswertung",
        sources=(_src("band_pivot", "Soll-EG-Spanne", "Passend", "Abweichend", "Unbesetzt", "Nicht gefunden"),),
        calculations=(
            _ref(COMPACT_FILE, "render_ist_soll_koepfe_tab"),
            _ref(COMPACT_FILE, "_build_soll_ist_band_fit_summary"),
        ),
        formula="Fit-Zusammenfassung je Soll-EG-Spanne; Passquote = Passend / SOLL, Kapazitaetsluecke als Rest zur SOLL-Logik.",
        filters=("aktiver Kompakt-Filterkontext", "gueltige Soll-Entgeltgruppe"),
        data_lineage="band_pivot -> _build_soll_ist_band_fit_summary -> chart/table/export",
        tests=("test_build_soll_ist_band_fit_summary_splits_passend_and_abweichend",),
        validation_status="technisch bestaetigt",
    ),
    LineageSpec(
        lineage_id="1-05",
        label="Kompakt Soll-Ist Koepfe Detailaufschluesselung",
        page="Kompakt",
        section="IST vs SOLL Koepfe Detail",
        display_type="Drilldown, Charts, Excel-Download",
        unit="Planstellenanzahl",
        data_basis="Ausgewaehlte Soll-EG-Spanne",
        sources=(_src("detail", "_Soll_EG_Band", "_Ist_EG", "_Klasse", "Organisationseinheit", "Planstelle"),),
        calculations=(
            _ref(COMPACT_FILE, "render_ist_soll_koepfe_tab"),
            _ref(COMPACT_FILE, "_aggregate_detail_breakdown"),
            _ref(COMPACT_FILE, "_aggregate_detail_breakdown_stacked"),
            _ref(COMPACT_FILE, "_aggregate_direction_split"),
        ),
        formula="Klassifizierung je Planstelle: Unbesetzt, Nicht gefunden, Untergruppiert, Uebergruppiert oder Passend; Export enthaelt Uebersicht, Ist-Eingruppierung, OE-, Planstellentyp- und Richtungssplits.",
        filters=("aktiver Kompakt-Filterkontext", "ausgewaehlte Soll-EG-Spanne", "ausgewaehlte Detailteilmenge"),
        data_lineage="work_df -> ausgewaehlte Soll-EG-Spanne -> _Klasse -> breakdown tables -> Detail-Excel",
        tests=("test_render_ist_soll_koepfe_tab_detail_excel_export_matches_charts_and_hover",),
        validation_status="technisch bestaetigt",
    ),
    LineageSpec(
        lineage_id="1-06",
        label="Kompakt Verguetung Planebene",
        page="Kompakt",
        section="IST vs SOLL nach Entgeltgruppen",
        display_type="Chart, Tabelle, Excel-Download",
        unit="MAK, Koepfe oder EUR",
        data_basis="Kompakt-Verguetungsdaten",
        sources=(_src("comp_df", "Ist_Entgeltgruppe", "Soll_Entgeltgruppe", "IST_MAK", "SOLL_MAK_View", "IST_EUR", "SOLL_EUR_View"),),
        calculations=(
            _ref(COMPACT_FILE, "render_compensation_planlevel_section"),
            _ref(COMPACT_FILE, "build_compact_compensation_planlevel_df"),
            _ref(COMPACT_FILE, "_build_compensation_chart_source"),
            _ref(COMPACT_FILE, "_create_eg_ist_vs_soll_chart"),
            _ref(COMPACT_FILE, "_build_eg_summary_table"),
        ),
        formula="IST und SOLL werden je Entgeltgruppe aggregiert; Delta = IST - SOLL; Delta % = Delta / SOLL, wenn SOLL > 0.",
        filters=("aktiver Kompakt-Filterkontext", "Exklusionslogik", "globale Kennzahl MAK/Koepfe/EUR"),
        data_lineage="prepared_df -> build_compact_compensation_planlevel_df -> _build_compensation_chart_source -> chart/table/export",
        tests=("test_kompakt_export_calls_declare_lineage_ids",),
        validation_status="technisch bestaetigt",
    ),
    LineageSpec(
        lineage_id="1-07",
        label="Kompakt Qualifikationsspannweite",
        page="Kompakt",
        section="Qualifikation pro Planstelle",
        display_type="Chart, Tabelle, Excel-Download",
        unit="Ausbildungsordinal und Personenanzahl",
        data_basis="Planstellen mit mindestens zwei Personen mit bekannter Ausbildung",
        sources=(_src("range_df", "Planstelle", "min_label", "n_min", "mean_label", "max_label", "n_max", "count"),),
        calculations=(
            _ref(COMPACT_FILE, "_render_education_range_section_clean"),
            _ref(COMPACT_FILE, "create_education_range_data"),
            _ref(COMPACT_FILE, "create_education_range_chart"),
        ),
        formula="Ausbildung wird in eine Ordnung uebersetzt; je Planstelle werden Minimum, Mittelwert, Maximum und die Haeufigkeiten der Randwerte berechnet.",
        filters=("aktiver Kompakt-Filterkontext", "mindestens zwei bekannte Ausbildungswerte je Planstelle"),
        data_lineage="filtered dashboard data -> create_education_range_data -> create_education_range_chart -> table/export",
        tests=("test_kompakt_export_calls_declare_lineage_ids",),
        validation_status="technisch bestaetigt",
    ),
    LineageSpec(
        lineage_id="1-08",
        label="Kompakt Einzel-Breakdown",
        page="Kompakt",
        section="IST-Breakdowns",
        display_type="Horizontales Balkendiagramm, Tabelle, Excel-Download",
        unit="MAK, Koepfe oder EUR",
        data_basis="Aktuelle gefilterte Mitarbeiter- und Planstellendaten",
        sources=(_src("breakdown_df", "Kategorie", "IST", "Anteil"),),
        calculations=(
            _ref(COMPACT_FILE, "_render_single_breakdown_clean"),
            _ref(COMPACT_FILE, "create_breakdown_table"),
            _ref(COMPACT_FILE, "create_horizontal_bar_chart"),
        ),
        formula="Gruppierung nach aktueller Dimension; IST = Summe der gewaehlten Wertspalte; Anteil = IST / Gesamt-IST der Tabelle.",
        filters=("aktiver Kompakt-Filterkontext", "Dimension aus Themenfeld", "globale Kennzahl MAK/Koepfe/EUR"),
        data_lineage="filtered dashboard data -> create_breakdown_table -> create_horizontal_bar_chart -> table/export",
        tests=("test_kompakt_export_calls_declare_lineage_ids",),
        validation_status="technisch bestaetigt",
    ),
    LineageSpec(
        lineage_id="1-09",
        label="Kompakt Einzel-Vergleich IST vs SOLL",
        page="Kompakt",
        section="IST-vs-SOLL-Breakdowns",
        display_type="Vergleichschart, Tabelle, Excel-Download",
        unit="MAK oder EUR",
        data_basis="Aktuelle gefilterte Mitarbeiter- und Planstellendaten",
        sources=(_src("breakdown_df", "Kategorie", "IST", "SOLL", "Delta", "Erfuellungsgrad"),),
        calculations=(
            _ref(COMPACT_FILE, "_render_single_comparison_clean"),
            _ref(COMPACT_FILE, "create_breakdown_table"),
            _ref(COMPACT_FILE, "create_comparison_chart"),
        ),
        formula="Gruppierung nach aktueller Dimension; IST und SOLL sind Summen der gewaehlten Spalten; Delta = IST - SOLL; Erfuellungsgrad = IST / SOLL.",
        filters=("aktiver Kompakt-Filterkontext", "Dimension aus Themenfeld", "globale Kennzahl MAK/EUR"),
        data_lineage="filtered dashboard data -> create_breakdown_table(include_soll=True) -> create_comparison_chart -> table/export",
        tests=("test_kompakt_export_calls_declare_lineage_ids",),
        validation_status="technisch bestaetigt",
    ),
    LineageSpec(
        lineage_id="1-10",
        label="Kompakt Verguetungsklassen Breakdown",
        page="Kompakt",
        section="Verguetungsklassen",
        display_type="Gestapeltes Tarifdiagramm, Tabelle, Excel-Download",
        unit="MAK, Koepfe oder EUR",
        data_basis="Tarifgruppe und Stufe der gefilterten Daten",
        sources=(_src("breakdown_df", "Entgeltgruppe", "Stufe", "Wert"),),
        calculations=(
            _ref(COMPACT_FILE, "_render_single_breakdown_clean"),
            _ref(COMPACT_FILE, "create_stacked_tariff_breakdown_table"),
            _ref(COMPACT_FILE, "create_stacked_tariff_chart"),
        ),
        formula="Tarifdaten werden nach Entgeltgruppe und Stufe aggregiert; Zellen zeigen die Summe der gewaehlten Wertspalte.",
        filters=("aktiver Kompakt-Filterkontext", "Dimension Verguetungsklasse", "globale Kennzahl MAK/Koepfe/EUR"),
        data_lineage="filtered dashboard data -> create_stacked_tariff_breakdown_table -> create_stacked_tariff_chart -> table/export",
        tests=("test_kompakt_export_calls_declare_lineage_ids",),
        validation_status="technisch bestaetigt",
    ),
    LineageSpec(
        lineage_id="1-11",
        label="Kompakt Verguetungsklassen Vergleich IST vs SOLL",
        page="Kompakt",
        section="Verguetungsklassen IST vs SOLL",
        display_type="Gestapeltes Tarif-Vergleichsdiagramm, Tabelle, Excel-Download",
        unit="MAK oder EUR",
        data_basis="Tarifgruppe und Stufe der gefilterten IST- und SOLL-Daten",
        sources=(_src("breakdown_df", "Entgeltgruppe", "Stufe", "IST", "SOLL"),),
        calculations=(
            _ref(COMPACT_FILE, "_render_single_comparison_clean"),
            _ref(COMPACT_FILE, "create_stacked_tariff_breakdown_table"),
            _ref(COMPACT_FILE, "create_stacked_tariff_comparison_chart"),
        ),
        formula="Tarifvergleich nach Entgeltgruppe und Stufe; Chart vergleicht aggregierte IST- und SOLL-Werte, Export dokumentiert die zugrunde liegende Tarifmatrix.",
        filters=("aktiver Kompakt-Filterkontext", "Dimension Verguetungsklasse", "globale Kennzahl MAK/EUR"),
        data_lineage="filtered dashboard data -> create_stacked_tariff_breakdown_table/create_stacked_tariff_comparison_chart -> table/export",
        tests=("test_kompakt_export_calls_declare_lineage_ids",),
        validation_status="technisch bestaetigt",
    ),
    LineageSpec(
        lineage_id="2-01",
        label="Datenintegritaets-Evaluation",
        page="Einstellungen",
        section="Datenintegritaet",
        display_type="Excel-Report",
        unit="Anzahl Abweichungen",
        data_basis="Upload Mitarbeiter.xlsx und Planstellen.xlsx",
        sources=(
            _src("Mitarbeiter.xlsx", "PersNr"),
            _src("Planstellen.xlsx", "Personalnummer"),
        ),
        calculations=(
            _ref(DATA_INTEGRITY_FILE, "check_mitarbeiter_planstellen_integrity"),
            _ref(DATA_INTEGRITY_FILE, "build_integrity_report_excel"),
            _ref(DATA_INTEGRITY_FILE, "_sanitize_excel_cell"),
            _ref(DATA_INTEGRITY_FILE, "_stringify_cell"),
        ),
        formula=(
            "Personalnummern werden normalisiert; besetzte Planstellen ohne Mitarbeiter-Match, "
            "Mitarbeiter ohne besetzte Planstelle und doppelte PersNr in Mitarbeiter.xlsx werden gezaehlt."
        ),
        filters=("Upload-Dateien", "Schema-Pflichtspalten PersNr/Personalnummer"),
        data_lineage=(
            "global_uploads -> pd.read_excel -> check_mitarbeiter_planstellen_integrity -> "
            "DataIntegrityReport -> build_integrity_report_excel"
        ),
        tests=(
            "test_detects_besetzte_planstelle_ohne_mitarbeiter_match",
            "test_detects_mitarbeiter_ohne_planstelle",
            "test_detects_duplicate_personalnummer_in_mitarbeiter",
            "test_excel_export_has_no_formula_injection_from_malicious_upload_data",
            "test_integrity_excel_export_contains_lineage_report",
        ),
        validation_status="technisch bestaetigt",
        notes="Der Report laeuft nur bei Upload eigener Mitarbeiter- und Planstellen-Dateien.",
    ),
    LineageSpec(
        lineage_id="2-02",
        label="Originaldaten Upload-Templates",
        page="Einstellungen",
        section="Datenmanagement",
        display_type="Excel-Template",
        unit="Spalten und Dropdown-Werte",
        data_basis="TEMPLATE_SPECS aus dataloader/upload_templates.py",
        sources=(_src("TEMPLATE_SPECS", "columns", "choices", "strict", "row_count", "sheet_name"),),
        calculations=(
            _ref(UPLOAD_TEMPLATES_FILE, "generate_upload_template_bytes"),
            _ref(UPLOAD_TEMPLATES_FILE, "_column_width"),
        ),
        formula="Leere Excel-Vorlage je Uploadtyp; Header aus TEMPLATE_SPECS; Choice-Spalten erhalten Datenvalidierung gegen ein verstecktes Listen-Sheet.",
        filters=("Template-Auswahl",),
        data_lineage="TEMPLATE_SPECS[spec_key] -> xlsxwriter workbook -> Upload-Template-Download",
        tests=(
            "test_generate_upload_template_has_expected_columns_and_hidden_lists_sheet",
            "test_upload_templates_contain_lineage_report",
        ),
        validation_status="technisch bestaetigt",
    ),
    LineageSpec(
        lineage_id="2-03",
        label="TVOED Upload-Template",
        page="Einstellungen",
        section="Datenmanagement",
        display_type="Excel-Template",
        unit="Tarifgruppen und Stufen",
        data_basis="config.settings.TARIFF_GROUPS",
        sources=(_src("TARIFF_GROUPS", "Entgeltgruppe", "Stufe 1-6"),),
        calculations=(_ref(UPLOAD_TEMPLATES_FILE, "generate_tvoed_template_bytes"),),
        formula="Leere TVOED-Entgelttabelle; Zeilen entsprechen TARIFF_GROUPS, Spalten entsprechen Stufen 1 bis 6.",
        filters=("Template-Auswahl TVOED",),
        data_lineage="TARIFF_GROUPS -> generate_tvoed_template_bytes -> TVOED_Template.xlsx",
        tests=(
            "test_generate_tvoed_template_matches_loader_layout",
            "test_tvoed_template_contains_lineage_report",
        ),
        validation_status="technisch bestaetigt",
    ),
    LineageSpec(
        lineage_id="2-04",
        label="Cluster Mapping Template",
        page="Einstellungen",
        section="Cluster-Management",
        display_type="Excel-Template",
        unit="Organisationseinheiten und Jobfamilies",
        data_basis="geladener Mitarbeiter-/Planstellen-Snapshot und Jobfamily-Definitionen",
        sources=(
            _src("df_ma", "Kuerzel OrgEinheit", "OrgEinheitNr", "Organisationseinheit", "Planstelle"),
            _src("jf_definitions"),
        ),
        calculations=(_ref(CLUSTER_MANAGER_FILE, "generate_template_bytes"),),
        formula="Eindeutige Organisationseinheiten und eindeutige Kombinationen aus Organisationseinheit und Planstelle werden als Mapping-Vorlage exportiert.",
        filters=("aktueller Datenstand",),
        data_lineage="load_and_prepare_data -> generate_template_bytes -> Cluster-Template.xlsx",
        tests=("test_cluster_template_contains_lineage_report",),
        validation_status="technisch bestaetigt",
    ),
    LineageSpec(
        lineage_id="2-05",
        label="Jobfamily Definitionen Export",
        page="Setup-Wizard",
        section="Definitionen exportieren",
        display_type="Excel-Export",
        unit="Jobfamilies, Patterns, manuelle Zuordnungen",
        data_basis="Jobfamily-Definitionsobjekt",
        sources=(_src("definitions", "jobfamilies", "patterns", "manual_assignments", "manual_overrides", "metadata"),),
        calculations=(_ref(IMPORT_EXPORT_FILE, "export_to_excel"),),
        formula="Definitionen werden in Uebersicht, Patterns, Manuelle Zuordnungen und Metadata exportiert.",
        filters=("aktuelle Jobfamily-Definitionen",),
        data_lineage="definitions -> export_to_excel -> jobfamilies_export.xlsx",
        tests=("test_jobfamily_definition_excel_contains_lineage_report",),
        validation_status="technisch bestaetigt",
    ),
    LineageSpec(
        lineage_id="2-06",
        label="Jobfamily Mapping Report",
        page="Setup-Wizard",
        section="Definitionen exportieren",
        display_type="Excel-Report",
        unit="Planstellen, Jobfamilies, Match-Typen",
        data_basis="Job-Daten und Jobfamily-Definitionen",
        sources=(
            _src("df", "Planstelle", "Jobfamily", "Jobfamily_match_type"),
            _src("definitions", "jobfamilies.patterns"),
        ),
        calculations=(_ref(IMPORT_EXPORT_FILE, "export_mapping_report"),),
        formula="Jede Planstelle wird mit Jobfamily und Match-Typ exportiert; bei Pattern-Matches wird das erste passende Pattern ausgewiesen; Statistik-Sheet zaehlt Mapping-Quote und Verteilungen.",
        filters=("aktueller Mapping-Datenstand", "Spaltennamen fuer Planstelle/Jobfamily/Match-Typ"),
        data_lineage="df + definitions -> export_mapping_report -> mapping_report.xlsx",
        tests=("test_mapping_report_excel_contains_lineage_report",),
        validation_status="technisch bestaetigt",
    ),
    LineageSpec(
        lineage_id="8-13",
        label="Jobgruppen Top-Filter",
        page=JOB_PAGE,
        section="Top-Filter",
        display_type="Filterwirkung",
        unit="Auswahl",
        data_basis="IST-Snapshot",
        sources=(_src("prepared_df", "Jobfamily", "Headcount", "MAK_Reporting"),),
        calculations=(
            _ref(JOB_FILE, "_build_jobfamily_ranking_frame"),
            _ref(JOB_FILE, "_apply_jobfamily_top_filters"),
        ),
        formula="Ranking je Jobfamily; UNMAPPED ausschliessen; Mindestgroesse anwenden; sortieren; danach Top-N begrenzen.",
        filters=COMMON_ANALYSIS_FILTERS,
        data_lineage="load_and_prepare_data -> prepare_compact_data -> apply_filters -> mapped_df -> ranking_df -> display_jobfamilies",
        tests=(
            "test_jobfamily_current_metric_sort_uses_visible_mak_not_headcount",
            "test_jobfamily_min_size_filter_applies_before_top_n",
        ),
        notes="Default Top-N ist 8; fachliche Bestaetigung bleibt empfohlen.",
    ),
    LineageSpec(
        lineage_id="8-14",
        label="Jobgruppen Rangliste",
        page=JOB_PAGE,
        section="Rangliste",
        display_type="Chart, Tabelle, Download",
        unit="Koepfe, MAK oder EUR",
        data_basis="IST-Snapshot",
        sources=(_src("mapped_df", "Jobfamily", "PersNr", "Headcount", "MAK_Reporting", "EUR_Reporting"),),
        calculations=(_ref(JOB_FILE, "_render_jobfamily_rangliste"),),
        formula="Summe der gewaehlten Kennzahl je Jobfamily ohne Vakanzen; Anzeige und Export folgen display_jobfamilies.",
        filters=COMMON_ANALYSIS_FILTERS,
        data_lineage="snapshot_df -> prepare_compact_data -> apply_filters -> mapped_df -> create_breakdown_table -> chart/table/export",
        tests=("test_jobfamily_ranking_download_matches_visible_display_order_and_values",),
        notes="EUR ist Kennzahl, aber keine Sortieroption; Sortierung faellt in EUR-Sicht auf MAK zurueck.",
    ),
    LineageSpec(
        lineage_id="8-15",
        label="Jobgruppen Zusammensetzung",
        page=JOB_PAGE,
        section="Zusammensetzung",
        display_type="Chart, Tabelle, Download",
        unit="Koepfe, MAK oder EUR",
        data_basis="IST-Snapshot",
        sources=(_src("mapped_df", "Jobfamily", "Geschlecht", "Alterskohorte", "Beschaeftigungsstatus", "MAK_Reporting", "EUR_Reporting"),),
        calculations=(
            _ref(JOB_FILE, "_render_jobfamily_split_block"),
            _ref(JOB_FILE, "_aggregate_jobfamily_split"),
        ),
        formula="Gruppierung nach Jobfamily und Split-Dimension; Summe der gewaehlten Kennzahl; Pivot fuer Tabelle und Export.",
        filters=COMMON_ANALYSIS_FILTERS,
        data_lineage="mapped_df -> _aggregate_jobfamily_split -> chart_df/pivot_df -> table/export",
        tests=("test_jobfamily_split_block_uses_same_pivot_for_table_and_export",),
    ),
    LineageSpec(
        lineage_id="8-16",
        label="Jobgruppen Tarifstruktur",
        page=JOB_PAGE,
        section="Personalstruktur nach Tarifgruppe",
        display_type="Tabelle, Download",
        unit="Koepfe und MAK",
        data_basis="IST-Snapshot",
        sources=(_src("mapped_df", "Jobfamily", "TrfGr", "PersNr", "MAK_Reporting"),),
        calculations=(
            _ref(JOB_FILE, "_resolve_role_metric"),
            _ref(JOB_FILE, "_render_role_breakdown_block"),
        ),
        formula="EUR-Sicht faellt fuer Tarifstruktur auf MAK zurueck; Vakanzen werden ausgeschlossen; Koepfe, MAK und Durchschnitts-MAK je Jobfamily.",
        filters=COMMON_ANALYSIS_FILTERS,
        data_lineage="mapped_df -> _resolve_role_metric -> _build_role_summary_table -> Tarifgruppenaggregation",
        tests=("test_role_summary_tables_exclude_vacancies_and_fallback_eur_to_mak",),
        notes="Tarifstruktur ist eine Struktur- und Kapazitaetsanalyse, keine Kostenanalyse.",
    ),
    LineageSpec(
        lineage_id="8-17",
        label="Jobgruppen Datenqualitaet",
        page=JOB_PAGE,
        section="Datenqualitaet",
        display_type="Tabelle, KPI, Download",
        unit="Koepfe, MAK oder EUR",
        data_basis="IST-Snapshot",
        sources=(_src("filtered_df", "Jobfamily", "Planstelle", "Headcount", "MAK_Reporting", "EUR_Reporting"),),
        calculations=(_ref(JOB_FILE, "_render_data_quality_block"),),
        formula="Trennung in mapped_df und unmapped_df anhand Jobfamily != UNMAPPED; Ausweis des Restvolumens.",
        filters=("Sidebar-Filter", "globale Kennzahl"),
        data_lineage="filtered_df -> normalize_jobfamily_column -> mapped_df/unmapped_df -> quality KPIs/tables",
        tests=("test_lineage_registry_contains_data_quality_specs",),
        validation_status="technisch teilweise bestaetigt",
    ),
    LineageSpec(
        lineage_id="9-13",
        label="Organisationseinheiten Top-Filter",
        page=ORG_PAGE,
        section="Top-Filter",
        display_type="Filterwirkung",
        unit="Auswahl",
        data_basis="IST-Snapshot",
        sources=(_src("prepared_df", "Organisationseinheit", "Headcount", "MAK_Reporting"),),
        calculations=(
            _ref(ORG_FILE, "_build_orgunit_ranking_frame"),
            _ref(ORG_FILE, "_apply_orgunit_top_filters"),
        ),
        formula="Ranking je Organisationseinheit; nicht zugeordnete OEs ausschliessen; Mindestgroesse anwenden; sortieren; danach Top-N begrenzen.",
        filters=COMMON_ANALYSIS_FILTERS,
        data_lineage="load_and_prepare_data -> prepare_compact_data -> apply_filters -> mapped_df -> ranking_df -> display_orgs",
        tests=("test_orgunit_top_filters_reuse_ranking_for_min_size_sort_and_simulation_focus",),
    ),
    LineageSpec(
        lineage_id="9-14",
        label="Organisationseinheiten Rangliste",
        page=ORG_PAGE,
        section="Rangliste",
        display_type="Chart, Tabelle, Download",
        unit="Koepfe, MAK oder EUR",
        data_basis="IST-Snapshot",
        sources=(_src("mapped_df", "Organisationseinheit", "PersNr", "Personalnummer", "MAK_Reporting", "EUR_Reporting"),),
        calculations=(_ref(ORG_FILE, "_render_org_rangliste"),),
        formula="Summe der gewaehlten Kennzahl je Organisationseinheit ohne Vakanzen; Koepfe zaehlt eindeutige PersNr/Personalnummer.",
        filters=COMMON_ANALYSIS_FILTERS,
        data_lineage="snapshot_df -> prepare_compact_data -> apply_filters -> mapped_df -> _render_org_rangliste -> chart/table/export",
        tests=("test_orgunit_ranking_download_matches_visible_display_order_and_values",),
        notes="EUR ist Kennzahl, aber keine Sortieroption; Sortierung faellt in EUR-Sicht auf MAK zurueck.",
    ),
    LineageSpec(
        lineage_id="9-15",
        label="Organisationseinheiten Zusammensetzung",
        page=ORG_PAGE,
        section="Zusammensetzung",
        display_type="Chart, Tabelle, Download",
        unit="Koepfe, MAK oder EUR",
        data_basis="IST-Snapshot",
        sources=(_src("mapped_df", "Organisationseinheit", "Geschlecht", "Alterskohorte", "Beschaeftigungsstatus", "MAK_Reporting", "EUR_Reporting"),),
        calculations=(
            _ref(ORG_FILE, "_render_org_split_block"),
            _ref(ORG_FILE, "_aggregate_org_split"),
        ),
        formula="Gruppierung nach Organisationseinheit und Split-Dimension; Summe der gewaehlten Kennzahl; Pivot fuer Tabelle und Export.",
        filters=COMMON_ANALYSIS_FILTERS,
        data_lineage="mapped_df -> _aggregate_org_split -> chart_df/pivot_df -> table/export",
        tests=("test_orgunit_split_block_uses_same_pivot_for_table_and_export",),
    ),
    LineageSpec(
        lineage_id="9-16",
        label="Organisationseinheiten Tarifstruktur",
        page=ORG_PAGE,
        section="Personalstruktur nach Tarifgruppe",
        display_type="Tabelle, Download",
        unit="Koepfe und MAK",
        data_basis="IST-Snapshot",
        sources=(_src("mapped_df", "Organisationseinheit", "TrfGr", "PersNr", "MAK_Reporting"),),
        calculations=(
            _ref(ORG_FILE, "_resolve_role_metric"),
            _ref(ORG_FILE, "_render_role_breakdown_block"),
        ),
        formula="EUR-Sicht faellt fuer Tarifstruktur auf MAK zurueck; Vakanzen werden ausgeschlossen; Koepfe, MAK und Durchschnitts-MAK je OE.",
        filters=COMMON_ANALYSIS_FILTERS,
        data_lineage="mapped_df -> _resolve_role_metric -> _build_role_summary_table -> Tarifgruppenaggregation",
        tests=("test_role_summary_tables_exclude_vacancies_and_fallback_eur_to_mak",),
        notes="Tarifstruktur ist eine Struktur- und Kapazitaetsanalyse, keine Kostenanalyse.",
    ),
    LineageSpec(
        lineage_id="9-17",
        label="Organisationseinheiten Datenqualitaet",
        page=ORG_PAGE,
        section="Datenqualitaet",
        display_type="Tabelle, KPI, Download",
        unit="Koepfe, MAK oder EUR",
        data_basis="IST-Snapshot",
        sources=(_src("filtered_df", "Organisationseinheit", "Headcount", "MAK_Reporting", "EUR_Reporting"),),
        calculations=(_ref(ORG_FILE, "_render_data_quality_block"),),
        formula="Trennung in mapped_df und unmapped_df anhand Organisationseinheit != Nicht zugeordnet; Ausweis des Restvolumens.",
        filters=("Sidebar-Filter", "globale Kennzahl"),
        data_lineage="filtered_df -> _normalize_org_column -> mapped_df/unmapped_df -> quality KPIs/tables",
        tests=("test_lineage_registry_contains_data_quality_specs",),
        validation_status="technisch teilweise bestaetigt",
    ),
    LineageSpec(
        lineage_id="10-01",
        label="OE-Simulation KPI-Header",
        page=ORG_SIM_PAGE,
        section="KPI-Header",
        display_type="KPI",
        unit="Koepfe, MAK oder EUR",
        data_basis="Future-Snapshot aus Simulation",
        sources=(_src("compact_sim_prepared_df", "Organisationseinheit", "PersNr", "MAK_Reporting", "EUR_Reporting"),),
        calculations=(
            _ref(ORG_SIM_FILE, "main"),
            _ref(ORG_FILE, "render_orgunit_analysis_page"),
            _ref(ORG_FILE, "_build_kpis"),
        ),
        formula="KPI-Formeln der IST-OE-Analyse auf compact_sim_prepared_df; kein Rueckfall auf IST-Daten.",
        filters=("Sidebar-Filter", "globale Kennzahl"),
        data_lineage="simulate_compact_snapshot -> future_snapshot_df -> prepare_compact_data -> compact_sim_prepared_df -> _build_kpis",
        tests=("test_orgunit_simulation_page_uses_computed_future_snapshot_and_preserves_values",),
        parameters=(
            ParameterSpec("compact_sim_target_date_cached", "st.session_state"),
            ParameterSpec("compact_sim_metadata", "st.session_state"),
        ),
    ),
    LineageSpec(
        lineage_id="10-02",
        label="OE-Simulation Rangliste",
        page=ORG_SIM_PAGE,
        section="Rangliste",
        display_type="Chart, Tabelle, Download",
        unit="Koepfe, MAK oder EUR",
        data_basis="Future-Snapshot aus Simulation",
        sources=(_src("compact_sim_prepared_df", "Organisationseinheit", "PersNr", "MAK_Reporting", "EUR_Reporting"),),
        calculations=(
            _ref(ORG_SIM_FILE, "main"),
            _ref(ORG_FILE, "_render_org_rangliste"),
        ),
        formula="Summe der gewaehlten Kennzahl je Organisationseinheit im Future-Snapshot ohne Vakanzen.",
        filters=COMMON_ANALYSIS_FILTERS,
        data_lineage="future_snapshot_df -> compact_sim_prepared_df -> apply_filters -> mapped_df -> _render_org_rangliste",
        tests=(
            "test_orgunit_ranking_download_matches_visible_display_order_and_values",
            "test_orgunit_simulation_page_uses_computed_future_snapshot_and_preserves_values",
        ),
    ),
    LineageSpec(
        lineage_id="10-03",
        label="OE-Simulation IST-Vergleich",
        page=ORG_SIM_PAGE,
        section="IST-Vergleich",
        display_type="Chart, Tabelle, Download",
        unit="Koepfe, MAK oder EUR; Delta; Prozent",
        data_basis="Future-Snapshot und Status-Quo-Snapshot aus Simulation",
        sources=(
            _src("compact_sim_prepared_df", "Organisationseinheit", "PersNr", "MAK_Reporting", "EUR_Reporting"),
            _src("compact_sim_status_quo_df", "Organisationseinheit", "PersNr", "MAK_Reporting", "EUR_Reporting"),
            _src("compact_sim_audit_tables.Abgaenge_Events_Raw", "headcount_change", "mak_change"),
        ),
        calculations=(
            _ref(ORG_FILE, "_render_org_rangliste_comparison"),
            _ref(ORG_FILE, "_build_org_metric_comparison"),
        ),
        formula="Delta = Simulation - IST; Delta % = Delta / IST; bei IST = 0 wird Delta % als 0 gesetzt.",
        filters=COMMON_ANALYSIS_FILTERS + ("Vergleichstoggle", "Simulationsfokus"),
        data_lineage="future/status quo snapshots -> apply_filters -> _build_org_metric_comparison -> chart/table/export",
        tests=(
            "test_orgunit_comparison_summary_combines_ist_simulation_delta_and_departures",
            "test_orgunit_comparison_download_matches_visible_columns_and_raw_values",
        ),
    ),
    LineageSpec(
        lineage_id="10-04",
        label="OE-Simulation Abgaenge",
        page=ORG_SIM_PAGE,
        section="Abgaenge",
        display_type="Chart, Tabelle, Download",
        unit="Anzahl Personen; MAK",
        data_basis="Future-Audit-Events aus Simulation",
        sources=(_src("compact_sim_audit_tables.Abgaenge_Events_Raw", "Organisationseinheit", "persnr", "headcount_change", "mak_change"),),
        calculations=(
            _ref(ORG_SIM_FILE, "_get_departure_events"),
            _ref(ORG_FILE, "_build_departure_org_summary"),
        ),
        formula="Filter auf headcount_change < 0; Abgaenge = abs(headcount_change); MAK-Verlust = abs(mak_change); Aggregation je OE.",
        filters=("Sidebar-Filter", "Vergleichstoggle", "Simulationsfokus"),
        data_lineage="simulate_compact_snapshot -> audit_tables.Abgaenge_Events_Raw -> _get_departure_events -> _build_departure_org_summary",
        tests=("test_orgunit_simulation_departure_toggle_aggregates_company_leavers_by_org_unit",),
    ),
    LineageSpec(
        lineage_id="10-05",
        label="OE-Simulation Zusammensetzung",
        page=ORG_SIM_PAGE,
        section="Zusammensetzung",
        display_type="Chart, Tabelle, Download",
        unit="Koepfe, MAK oder EUR",
        data_basis="Future-Snapshot; optional Status-Quo-Snapshot",
        sources=(
            _src("compact_sim_prepared_df", "Organisationseinheit", "Geschlecht", "Alterskohorte", "Beschaeftigungsstatus"),
            _src("compact_sim_status_quo_df", "Organisationseinheit", "Geschlecht", "Alterskohorte", "Beschaeftigungsstatus"),
        ),
        calculations=(
            _ref(ORG_FILE, "_render_org_split_block"),
            _ref(ORG_FILE, "_build_split_comparison"),
        ),
        formula="Ohne Vergleich Future-Aggregation; mit Vergleich outer merge von IST und Simulation plus Delta und Delta %.",
        filters=COMMON_ANALYSIS_FILTERS + ("Vergleichstoggle", "Simulationsfokus"),
        data_lineage="compact_sim_prepared_df/status_quo_df -> _aggregate_org_split or _build_split_comparison -> chart/table/export",
        tests=(
            "test_orgunit_split_block_uses_same_pivot_for_table_and_export",
            "test_orgunit_split_comparison_contains_ist_simulation_delta_and_preserves_order",
        ),
    ),
    LineageSpec(
        lineage_id="10-06",
        label="OE-Simulation Top-Filter und Simulationsfokus",
        page=ORG_SIM_PAGE,
        section="Top-Filter und Simulationsfokus",
        display_type="Filterwirkung",
        unit="Auswahl",
        data_basis="Future-Snapshot; optional Status-Quo-Snapshot und Audit-Events",
        sources=(
            _src("compact_sim_prepared_df", "Organisationseinheit", "MAK_Reporting"),
            _src("compact_sim_status_quo_df", "Organisationseinheit", "MAK_Reporting"),
            _src("compact_sim_audit_tables.Abgaenge_Events_Raw", "headcount_change", "mak_change"),
        ),
        calculations=(
            _ref(ORG_FILE, "_build_orgunit_ranking_frame"),
            _ref(ORG_FILE, "_apply_orgunit_top_filters"),
        ),
        formula="Ranking enthaelt Simulation, optional IST, Delta, Abgaenge und MAK-Verlust; Simulationsfokus filtert auf Delta != 0 oder Abgaenge > 0.",
        filters=COMMON_ANALYSIS_FILTERS + ("Vergleichstoggle", "Simulationsfokus"),
        data_lineage="future/status quo/audit -> ranking_df -> _apply_orgunit_top_filters -> display_orgs",
        tests=("test_orgunit_top_filters_reuse_ranking_for_min_size_sort_and_simulation_focus",),
    ),
    LineageSpec(
        lineage_id="10-07",
        label="OE-Simulation Excel-Downloads",
        page=ORG_SIM_PAGE,
        section="Excel-Downloads",
        display_type="Download",
        unit="Tabellen",
        data_basis="Future-Snapshot; optional Status-Quo-Snapshot und Audit-Events",
        sources=(
            _src("compact_sim_prepared_df"),
            _src("compact_sim_status_quo_df"),
            _src("compact_sim_audit_tables"),
        ),
        calculations=(
            _ref(ORG_FILE, "_render_org_rangliste"),
            _ref(ORG_FILE, "_render_org_rangliste_comparison"),
            _ref(ORG_FILE, "_render_org_split_block"),
        ),
        formula="Exportdaten stammen aus denselben Aggregations-DataFrames wie Chart und sichtbare Tabelle; Anzeige formatiert, Export numerisch.",
        filters=COMMON_ANALYSIS_FILTERS + ("Vergleichstoggle", "Simulationsfokus"),
        data_lineage="aggregation dataframe -> formatted UI table + numeric Excel export",
        tests=(
            "test_orgunit_ranking_download_matches_visible_display_order_and_values",
            "test_orgunit_comparison_download_matches_visible_columns_and_raw_values",
            "test_orgunit_split_block_uses_same_pivot_for_table_and_export",
        ),
    ),
    LineageSpec(
        lineage_id="11-01",
        label="Jobgruppen-Simulation KPI-Header",
        page=JOB_SIM_PAGE,
        section="KPI-Header",
        display_type="KPI",
        unit="Koepfe, MAK oder EUR",
        data_basis="Future-Snapshot aus Simulation",
        sources=(_src("compact_sim_prepared_df", "Jobfamily", "PersNr", "MAK_Reporting", "EUR_Reporting"),),
        calculations=(
            _ref(JOB_SIM_FILE, "main"),
            _ref(JOB_FILE, "render_jobfamily_analysis_page"),
            _ref(JOB_FILE, "_build_kpis"),
        ),
        formula="KPI-Formeln der IST-Jobgruppen-Analyse auf compact_sim_prepared_df; kein Rueckfall auf IST-Daten.",
        filters=("Sidebar-Filter", "globale Kennzahl"),
        data_lineage="simulate_compact_snapshot -> future_snapshot_df -> prepare_compact_data -> compact_sim_prepared_df -> _build_kpis",
        tests=("test_jobfamily_simulation_page_uses_computed_future_snapshot",),
        parameters=(
            ParameterSpec("compact_sim_target_date_cached", "st.session_state"),
            ParameterSpec("compact_sim_metadata", "st.session_state"),
        ),
    ),
    LineageSpec(
        lineage_id="11-02",
        label="Jobgruppen-Simulation Rangliste",
        page=JOB_SIM_PAGE,
        section="Rangliste",
        display_type="Chart, Tabelle, Download",
        unit="Koepfe, MAK oder EUR",
        data_basis="Future-Snapshot aus Simulation",
        sources=(_src("compact_sim_prepared_df", "Jobfamily", "PersNr", "MAK_Reporting", "EUR_Reporting"),),
        calculations=(
            _ref(JOB_SIM_FILE, "main"),
            _ref(JOB_FILE, "_render_jobfamily_rangliste"),
        ),
        formula="Summe der gewaehlten Kennzahl je Jobfamily im Future-Snapshot ohne Vakanzen; UNMAPPED wird ausgeschlossen.",
        filters=COMMON_ANALYSIS_FILTERS,
        data_lineage="future_snapshot_df -> compact_sim_prepared_df -> apply_filters -> mapped_df -> _render_jobfamily_rangliste",
        tests=(
            "test_jobfamily_ranking_download_matches_visible_display_order_and_values",
            "test_jobfamily_simulation_page_uses_computed_future_snapshot",
        ),
    ),
    LineageSpec(
        lineage_id="11-03",
        label="Jobgruppen-Simulation Zusammensetzung",
        page=JOB_SIM_PAGE,
        section="Zusammensetzung",
        display_type="Chart, Tabelle, Download",
        unit="Koepfe, MAK oder EUR",
        data_basis="Future-Snapshot aus Simulation",
        sources=(_src("compact_sim_prepared_df", "Jobfamily", "Geschlecht", "Alterskohorte", "Beschaeftigungsstatus"),),
        calculations=(
            _ref(JOB_FILE, "_render_jobfamily_split_block"),
            _ref(JOB_FILE, "_aggregate_jobfamily_split"),
        ),
        formula="Aggregation wie IST-Jobgruppen-Analyse, aber auf Future-Snapshot; Pivot fuer Tabelle und Export.",
        filters=COMMON_ANALYSIS_FILTERS,
        data_lineage="compact_sim_prepared_df -> apply_filters -> mapped_df -> _aggregate_jobfamily_split -> chart/table/export",
        tests=("test_jobfamily_split_block_uses_same_pivot_for_table_and_export",),
    ),
    LineageSpec(
        lineage_id="11-04",
        label="Jobgruppen-Simulation Top-Filter",
        page=JOB_SIM_PAGE,
        section="Top-Filter",
        display_type="Filterwirkung",
        unit="Auswahl",
        data_basis="Future-Snapshot aus Simulation",
        sources=(_src("compact_sim_prepared_df", "Jobfamily", "Headcount", "MAK_Reporting"),),
        calculations=(
            _ref(JOB_FILE, "_build_jobfamily_ranking_frame"),
            _ref(JOB_FILE, "_apply_jobfamily_top_filters"),
        ),
        formula="Ranking je Jobfamily; Mindestgroesse filtert nach Koepfen/MAK; Sortierung nutzt aktuelle Kennzahl, Koepfe oder MAK; Top-N danach.",
        filters=COMMON_ANALYSIS_FILTERS,
        data_lineage="compact_sim_prepared_df -> apply_filters -> mapped_df -> ranking_df -> _apply_jobfamily_top_filters -> display_jobfamilies",
        tests=(
            "test_jobfamily_current_metric_sort_uses_visible_mak_not_headcount",
            "test_jobfamily_min_size_filter_applies_before_top_n",
        ),
    ),
    LineageSpec(
        lineage_id="11-05",
        label="Jobgruppen-Simulation Excel-Downloads",
        page=JOB_SIM_PAGE,
        section="Excel-Downloads",
        display_type="Download",
        unit="Tabellen",
        data_basis="Future-Snapshot aus Simulation",
        sources=(_src("compact_sim_prepared_df"),),
        calculations=(
            _ref(JOB_FILE, "_render_jobfamily_rangliste"),
            _ref(JOB_FILE, "_render_jobfamily_split_block"),
        ),
        formula="Exportdaten stammen aus denselben Aggregations-DataFrames wie Chart und sichtbare Tabelle; Anzeige formatiert, Export numerisch.",
        filters=COMMON_ANALYSIS_FILTERS,
        data_lineage="aggregation dataframe -> formatted UI table + numeric Excel export",
        tests=(
            "test_jobfamily_ranking_download_matches_visible_display_order_and_values",
            "test_jobfamily_split_block_uses_same_pivot_for_table_and_export",
        ),
    ),
)

_SPECS_BY_ID = {spec.lineage_id: spec for spec in LINEAGE_SPECS}


def iter_lineage_specs() -> tuple[LineageSpec, ...]:
    """Return all registered lineage specs in stable order."""

    return LINEAGE_SPECS


def get_lineage_spec(lineage_id: str) -> LineageSpec:
    """Return one lineage spec or raise KeyError with a helpful message."""

    try:
        return _SPECS_BY_ID[lineage_id]
    except KeyError as exc:
        raise KeyError(f"Unknown lineage id: {lineage_id}") from exc


def get_lineage_specs(lineage_ids: Iterable[str]) -> tuple[LineageSpec, ...]:
    """Return lineage specs for an export context."""

    return tuple(get_lineage_spec(lineage_id) for lineage_id in lineage_ids)


def lineage_report_dataframe(lineage_ids: Iterable[str]):
    """Build a flat dataframe suitable for an Excel Lineage_Report sheet."""

    import pandas as pd

    rows = []
    for spec in get_lineage_specs(lineage_ids):
        rows.append(
            {
                "Lineage-ID": spec.lineage_id,
                "Label": spec.label,
                "Seite": spec.page,
                "Bereich": spec.section,
                "Darstellungstyp": spec.display_type,
                "Einheit": spec.unit,
                "Datenbasis": spec.data_basis,
                "Quellen": "; ".join(source.table for source in spec.sources),
                "Quellspalten": "; ".join(
                    sorted({column for source in spec.sources for column in source.columns})
                ),
                "Berechnungsfunktionen": "; ".join(
                    f"{ref.file_glob}:{ref.function_name}" for ref in spec.calculations
                ),
                "Formel": spec.formula,
                "Filterwirkung": "; ".join(spec.filters),
                "Data Lineage": spec.data_lineage,
                "Testnachweis": "; ".join(spec.tests),
                "Validierungsstatus": spec.validation_status,
                "Hinweise": spec.notes,
            }
        )
    return pd.DataFrame(rows)
